// This file is automatically generated by the Vite CLI.
// It is not recommended to modify this file directly.
// If you want to customize the entry point, please refer to the Vite documentation:
// https://vitejs.dev/guide/#scaffolding-your-first-vite-project
// https://vitejs.dev/guide/api-javascript.html#vite-api
import { createRoot } from "react-dom/client";
import "./index.css";
import App from "./App.jsx";

createRoot(document.getElementById("root")).render(<App />);
